import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./(components)/footer/footer";
import Navbar from "./(components)/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Free skill",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;600;700&display=swap"
        />
      </head>
      <body className={inter.className}>
        {/* <Navbar/> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
